name: javerage_timer
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  # CORREGIDO: Se reemplazó el espacio inválido por 2 espacios normales.
  sdk: '>=3.9.2 <4.0.0' # Es mejor usar un rango de versiones

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  bloc: ^9.1.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  wave: ^0.2.2
  audioplayers: ^6.5.1
  # MOVIDO: 'mocktail' se movió a dev_dependencies

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^5.0.0
  bloc_test: ^10.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7
  # AÑADIDO: 'mocktail' está en la sección correcta.
  mocktail: ^1.0.4 

flutter:
  uses-material-design: true
  
  # CORREGIDO: Añadí la carpeta del icono a los assets.
  assets:
    - assets/audio/
    - assets/icon/ # Asegúrate de que esta carpeta exista

flutter_launcher_icons:
  android: true
  ios: true # Habilitado para iOS, puedes poner 'false' si no lo necesitas
  image_path: "assets/icon/logo_app.png"

flutter_native_splash:
  color: "#0E1534"
  # CORREGIDO: Ruta estandarizada para usar la misma que el icono.
  image: "assets/icon/logo_app.png"

  android_12:
    # CORREGIDO: Ruta estandarizada
    image: "assets/icon/logo_app.png"
    color: "#0E1534"